import Infosys from "./assets/Infosys.png";
import Accenture from "./assets/Accenture.png";
import HCL from "./assets/HCL.png";
import Capgemini from "./assets/Capgemini.png";
import Lodha from "./assets/Lodha.png";
import TCS from "./assets/TCS.png";
import Redington from "./assets/Redington.png";
import Mphasis from "./assets/Mphasis.png";
import Wipro from "./assets/Wipro.png";
import LT from "./assets/LT.png";


const data=[{
    id: 1,
    icon:Infosys,
    company_name: "Infosys",
    email_address: "awile0@blinklist.com",
    phone_no: "888-342-3120",
    contact_person: "lgudgen0",
    facilitator: "...",
    sites: 18,
    tenants: 78,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 2,
    icon:Wipro,
    company_name: "Wipro",
    email_address: "amaldin1@wikipedia.org",
    phone_no: "925-588-4076",
    contact_person: "xsherry1",
    facilitator: "...",
    sites: 18,
    tenants: 47,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 3,
    icon:Accenture,
    company_name: "Accenture",
    email_address: "drosson2@aboutads.info",
    phone_no: "502-964-8748",
    contact_person: "dellif2",
    facilitator: "...",
    sites: 11,
    tenants: 15,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 4,
    icon:Capgemini,
    company_name: "Capgemini",
    email_address: "lhazeup3@so-net.ne.jp",
    phone_no: "947-765-3917",
    contact_person: "thaselden3",
    facilitator: "...",
    sites: 8,
    tenants: 20,
    tenant_groups: "...",
   actions: "..."
  }, {
    id: 5,
    icon:Lodha,
    company_name: "Lodha",
    email_address: "medwicker4@google.pl",
    phone_no: "452-228-4643",
    contact_person: "ecowgill4",
    facilitator: "...",
    sites: 26,
    tenants: 25,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 6,
    icon:TCS,
    company_name: "Tata Consultancy Services",
    email_address: "mvasentsov5@istockphoto.com",
    phone_no: "874-779-1971",
    contact_person: "tclaybourn5",
    facilitator: "...",
    sites: 31,
    tenants: 82,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 7,
    icon:HCL,
    company_name: "HCL",
    email_address: "smeak6@amazon.co.uk",
    phone_no: "467-686-5332",
    contact_person: "jtomaschke6",
    facilitator: "...",
    sites: 40,
    tenants: 25,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 8,
    icon:Mphasis,
    company_name: "Mphasis",
    email_address: "tbretton7@sphinn.com",
    phone_no: "641-178-0796",
    contact_person: "hpay7",
    facilitator: "...",
    sites: 42,
    tenants: 18,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 9,
    icon:Redington,
    company_name: "Redington",
    email_address: "mibbott8@epa.gov",
    phone_no: "586-983-2456",
    contact_person: "lridding8",
    facilitator: "...",
    sites: 11,
    tenants: 74,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 10,
    icon:LT,
    company_name: "Larsen & toubro",
    email_address: "rlangdon9@themeforest.net",
    phone_no: "361-978-2633",
    contact_person: "jkopps9",
    facilitator: "...",
    sites: 20,
    tenants: 82,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 11,
    company_name: "Skiba",
    email_address: "aturfitta@macromedia.com",
    phone_no: "460-975-5092",
    contact_person: "zhutchinsona",
    facilitator: "...",
    sites: 44,
    tenants: 69,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 12,
    company_name: "Yombu",
    email_address: "fbarracloughb@soundcloud.com",
    phone_no: "536-489-8669",
    contact_person: "adenricob",
    facilitator: "...",
    sites: 21,
    tenants: 41,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 13,
    company_name: "Fadeo",
    email_address: "sgeorgesc@nationalgeographic.com",
    phone_no: "818-283-5846",
    contact_person: "jdanec",
    facilitator: "...",
    sites: 28,
    tenants: 98,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 14,
    company_name: "Ainyx",
    email_address: "fgunbyd@yellowpages.com",
    phone_no: "132-464-5034",
    contact_person: "ibroomhalld",
    facilitator: "...",
    sites: 23,
    tenants: 27,
    tenant_groups: "...",
   actions: "..."
  }, {
    id: 15,
    company_name: "Mycat",
    email_address: "thughille@sina.com.cn",
    phone_no: "682-331-4874",
    contact_person: "cforseye",
    facilitator: "...",
    sites: 3,
    tenants: 33,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 16,
    company_name: "Lazzy",
   email_address: "iescoffreyf@imageshack.us",
    phone_no: "682-353-9264",
    contact_person: "rglasebrookf",
    facilitator: "...",
    sites: 5,
    tenants: 63,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 17,
    company_name: "Leenti",
   email_address: "emerritong@artisteer.com",
    phone_no: "144-662-5009",
    contact_person: "lbrownlieg",
    facilitator: "...",
    sites: 25,
    tenants: 90,
    tenant_groups: "...",
   actions: "..."
  }, {
    id: 18,
    company_name: "Dynazzy",
   email_address: "splacstoneh@domainmarket.com",
    phone_no: "595-540-1383",
    contact_person: "nchamberlainh",
    facilitator: "...",
    sites: 35,
    tenants: 82,
    tenant_groups: "...",
   actions: "..."
  }, {
    id: 19,
    company_name: "Katz",
    email_address: "fsanzi@dropbox.com",
    phone_no: "177-157-0228",
    contact_person: "mkeatesi",
    facilitator: "...",
    sites: 36,
    tenants: 91,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 20,
    company_name: "Kimia",
    email_address: "wbrazearj@gmpg.org",
    phone_no: "171-808-3179",
    contact_person: "owillmentj",
    facilitator: "...",
    sites: 33,
    tenants: 45,
    tenant_groups: "...",
   actions: "..."
  },
  {
    id: 21,
    company_name: "Emirates",
    email_address: "aturfitta@macromedia.com",
    phone_no: "460-975-5092",
    contact_person: "zhutchinsona",
    facilitator: "...",
    sites: 44,
    tenants: 69,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 22,
    company_name: "CTS",
    email_address: "fbarracloughb@soundcloud.com",
    phone_no: "536-489-8669",
    contact_person: "adenricob",
    facilitator: "...",
    sites: 21,
    tenants: 41,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 23,
    company_name: "IBM",
    email_address: "sgeorgesc@nationalgeographic.com",
    phone_no: "818-283-5846",
    contact_person: "jdanec",
    facilitator: "...",
    sites: 28,
    tenants: 98,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 24,
    company_name: "CISCO",
    email_address: "fgunbyd@yellowpages.com",
    phone_no: "132-464-5034",
    contact_person: "ibroomhalld",
    facilitator: "...",
    sites: 23,
    tenants: 27,
    tenant_groups: "...",
   actions: "..."
  }, {
    id: 25,
    company_name: "HP",
    email_address: "thughille@sina.com.cn",
    phone_no: "682-331-4874",
    contact_person: "cforseye",
    facilitator: "...",
    sites: 3,
    tenants: 33,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 26,
    company_name: "Google",
   email_address: "iescoffreyf@imageshack.us",
    phone_no: "682-353-9264",
    contact_person: "rglasebrookf",
    facilitator: "...",
    sites: 5,
    tenants: 63,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 27,
    company_name: "Amazon",
   email_address: "emerritong@artisteer.com",
    phone_no: "144-662-5009",
    contact_person: "lbrownlieg",
    facilitator: "...",
    sites: 25,
    tenants: 90,
    tenant_groups: "...",
   actions: "..."
  }, {
    id: 28,
    company_name: "Flipkart",
   email_address: "splacstoneh@domainmarket.com",
    phone_no: "595-540-1383",
    contact_person: "nchamberlainh",
    facilitator: "...",
    sites: 35,
    tenants: 82,
    tenant_groups: "...",
   actions: "..."
  }, {
    id: 29,
    company_name: "Mesho",
    email_address: "fsanzi@dropbox.com",
    phone_no: "177-157-0228",
    contact_person: "mkeatesi",
    facilitator: "...",
    sites: 36,
    tenants: 91,
    tenant_groups: "...",
    actions: "..."
  }, {
    id: 30,
    company_name: "Kimia",
    email_address: "wbrazearj@gmpg.org",
    phone_no: "171-808-3179",
    contact_person: "owillmentj",
    facilitator: "...",
    sites: 33,
    tenants: 45,
    tenant_groups: "...",
    actions: "..."}
]

  export default data;